// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuteMate.Server.Data;

#nullable disable

namespace MuteMate.Server.Migrations
{
    [DbContext(typeof(MuteMateDbContext))]
    partial class MuteMateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MuteMate.Server.Models.AnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "A",
                            IsCorrect = true,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 2,
                            Answer = "B",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 3,
                            Answer = "C",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Answer = "D",
                            IsCorrect = false,
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 5,
                            Answer = "N",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 6,
                            Answer = "B",
                            IsCorrect = true,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 7,
                            Answer = "T",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 8,
                            Answer = "F",
                            IsCorrect = false,
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 9,
                            Answer = "N",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 10,
                            Answer = "Z",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 11,
                            Answer = "C",
                            IsCorrect = true,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 12,
                            Answer = "K",
                            IsCorrect = false,
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 13,
                            Answer = "D",
                            IsCorrect = true,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 14,
                            Answer = "P",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 15,
                            Answer = "H",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 16,
                            Answer = "R",
                            IsCorrect = false,
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 17,
                            Answer = "G",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 18,
                            Answer = "R",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 19,
                            Answer = "I",
                            IsCorrect = false,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 20,
                            Answer = "E",
                            IsCorrect = true,
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 21,
                            Answer = "O",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 22,
                            Answer = "F",
                            IsCorrect = true,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 23,
                            Answer = "H",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 24,
                            Answer = "T",
                            IsCorrect = false,
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 25,
                            Answer = "M",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 26,
                            Answer = "U",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 27,
                            Answer = "G",
                            IsCorrect = true,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 28,
                            Answer = "E",
                            IsCorrect = false,
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 29,
                            Answer = "Q",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 30,
                            Answer = "H",
                            IsCorrect = true,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 31,
                            Answer = "S",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 32,
                            Answer = "Y",
                            IsCorrect = false,
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 33,
                            Answer = "A",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 34,
                            Answer = "G",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 35,
                            Answer = "L",
                            IsCorrect = false,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 36,
                            Answer = "I",
                            IsCorrect = true,
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 37,
                            Answer = "J",
                            IsCorrect = true,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 38,
                            Answer = "W",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 39,
                            Answer = "X",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 40,
                            Answer = "E",
                            IsCorrect = false,
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 41,
                            Answer = "J",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 42,
                            Answer = "V",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 43,
                            Answer = "K",
                            IsCorrect = true,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 44,
                            Answer = "N",
                            IsCorrect = false,
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 45,
                            Answer = "L",
                            IsCorrect = true,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 46,
                            Answer = "O",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 47,
                            Answer = "T",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 48,
                            Answer = "B",
                            IsCorrect = false,
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 49,
                            Answer = "P",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 50,
                            Answer = "M",
                            IsCorrect = true,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 51,
                            Answer = "S",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 52,
                            Answer = "Z",
                            IsCorrect = false,
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 53,
                            Answer = "J",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 54,
                            Answer = "F",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 55,
                            Answer = "U",
                            IsCorrect = false,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 56,
                            Answer = "N",
                            IsCorrect = true,
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 57,
                            Answer = "O",
                            IsCorrect = true,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 58,
                            Answer = "Q",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 59,
                            Answer = "K",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 60,
                            Answer = "H",
                            IsCorrect = false,
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 61,
                            Answer = "R",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 63,
                            Answer = "C",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 64,
                            Answer = "P",
                            IsCorrect = true,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 65,
                            Answer = "I",
                            IsCorrect = false,
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 66,
                            Answer = "M",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 67,
                            Answer = "Q",
                            IsCorrect = true,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 68,
                            Answer = "X",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 69,
                            Answer = "W",
                            IsCorrect = false,
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 70,
                            Answer = "D",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 71,
                            Answer = "Y",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 72,
                            Answer = "T",
                            IsCorrect = false,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 73,
                            Answer = "R",
                            IsCorrect = true,
                            QuestionId = 20
                        },
                        new
                        {
                            Id = 74,
                            Answer = "´Q",
                            IsCorrect = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 75,
                            Answer = "Á",
                            IsCorrect = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 76,
                            Answer = "H",
                            IsCorrect = true,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 77,
                            Answer = "I",
                            IsCorrect = false,
                            QuestionId = 21
                        },
                        new
                        {
                            Id = 78,
                            Answer = "T",
                            IsCorrect = true,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 79,
                            Answer = "F",
                            IsCorrect = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 80,
                            Answer = "N",
                            IsCorrect = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 81,
                            Answer = "M",
                            IsCorrect = false,
                            QuestionId = 22
                        },
                        new
                        {
                            Id = 82,
                            Answer = "J",
                            IsCorrect = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 83,
                            Answer = "X",
                            IsCorrect = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 84,
                            Answer = "U",
                            IsCorrect = true,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 85,
                            Answer = "L",
                            IsCorrect = false,
                            QuestionId = 23
                        },
                        new
                        {
                            Id = 86,
                            Answer = "O",
                            IsCorrect = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 87,
                            Answer = "B",
                            IsCorrect = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 88,
                            Answer = "E",
                            IsCorrect = false,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 89,
                            Answer = "V",
                            IsCorrect = true,
                            QuestionId = 24
                        },
                        new
                        {
                            Id = 90,
                            Answer = "V",
                            IsCorrect = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 91,
                            Answer = "W",
                            IsCorrect = true,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 92,
                            Answer = "G",
                            IsCorrect = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 93,
                            Answer = "M",
                            IsCorrect = false,
                            QuestionId = 25
                        },
                        new
                        {
                            Id = 94,
                            Answer = "X",
                            IsCorrect = true,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 95,
                            Answer = "K",
                            IsCorrect = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 96,
                            Answer = "Z",
                            IsCorrect = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 97,
                            Answer = "H",
                            IsCorrect = false,
                            QuestionId = 26
                        },
                        new
                        {
                            Id = 98,
                            Answer = "D",
                            IsCorrect = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 99,
                            Answer = "S",
                            IsCorrect = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 100,
                            Answer = "U",
                            IsCorrect = false,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 101,
                            Answer = "Y",
                            IsCorrect = true,
                            QuestionId = 27
                        },
                        new
                        {
                            Id = 102,
                            Answer = "Y",
                            IsCorrect = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 103,
                            Answer = "W",
                            IsCorrect = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 104,
                            Answer = "V",
                            IsCorrect = false,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 105,
                            Answer = "Z",
                            IsCorrect = true,
                            QuestionId = 28
                        },
                        new
                        {
                            Id = 106,
                            Answer = "Blue",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 107,
                            Answer = "Brown",
                            IsCorrect = true,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 108,
                            Answer = "Black",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 109,
                            Answer = "Red",
                            IsCorrect = false,
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 110,
                            Answer = "Red",
                            IsCorrect = true,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 111,
                            Answer = "White",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 112,
                            Answer = "Yellow",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 113,
                            Answer = "Purple",
                            IsCorrect = false,
                            QuestionId = 29
                        },
                        new
                        {
                            Id = 114,
                            Answer = "Brown",
                            IsCorrect = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 115,
                            Answer = "Green",
                            IsCorrect = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 116,
                            Answer = "Pink",
                            IsCorrect = false,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 117,
                            Answer = "Blue",
                            IsCorrect = true,
                            QuestionId = 30
                        },
                        new
                        {
                            Id = 118,
                            Answer = "Grey",
                            IsCorrect = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 119,
                            Answer = "Purple",
                            IsCorrect = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 120,
                            Answer = "Green",
                            IsCorrect = true,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 121,
                            Answer = "White",
                            IsCorrect = false,
                            QuestionId = 31
                        },
                        new
                        {
                            Id = 122,
                            Answer = "Red",
                            IsCorrect = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 123,
                            Answer = "Blue",
                            IsCorrect = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 124,
                            Answer = "Grey",
                            IsCorrect = false,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 125,
                            Answer = "Black",
                            IsCorrect = true,
                            QuestionId = 32
                        },
                        new
                        {
                            Id = 126,
                            Answer = "Green",
                            IsCorrect = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 127,
                            Answer = "White",
                            IsCorrect = true,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 128,
                            Answer = "Black",
                            IsCorrect = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 129,
                            Answer = "Pink",
                            IsCorrect = false,
                            QuestionId = 33
                        },
                        new
                        {
                            Id = 130,
                            Answer = "Yellow",
                            IsCorrect = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 131,
                            Answer = "Brown",
                            IsCorrect = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 132,
                            Answer = "Pink",
                            IsCorrect = true,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 133,
                            Answer = "Grey",
                            IsCorrect = false,
                            QuestionId = 34
                        },
                        new
                        {
                            Id = 134,
                            Answer = "Green",
                            IsCorrect = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 135,
                            Answer = "Purple",
                            IsCorrect = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 136,
                            Answer = "White",
                            IsCorrect = false,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 137,
                            Answer = "Yellow",
                            IsCorrect = true,
                            QuestionId = 35
                        },
                        new
                        {
                            Id = 138,
                            Answer = "Grey",
                            IsCorrect = true,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 139,
                            Answer = "Black",
                            IsCorrect = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 140,
                            Answer = "Brown",
                            IsCorrect = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 141,
                            Answer = "Red",
                            IsCorrect = false,
                            QuestionId = 36
                        },
                        new
                        {
                            Id = 142,
                            Answer = "Grey",
                            IsCorrect = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 143,
                            Answer = "Purple",
                            IsCorrect = true,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 144,
                            Answer = "Pink",
                            IsCorrect = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 145,
                            Answer = "Blue",
                            IsCorrect = false,
                            QuestionId = 37
                        },
                        new
                        {
                            Id = 146,
                            Answer = "images/animals/bear.png",
                            IsCorrect = true,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 147,
                            Answer = "images/animals/horse.png",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 148,
                            Answer = "images/animals/cat.png",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 149,
                            Answer = "images/animals/sheep.png",
                            IsCorrect = false,
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 150,
                            Answer = "images/animals/bear.png",
                            IsCorrect = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 151,
                            Answer = "images/animals/bird.png",
                            IsCorrect = true,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 152,
                            Answer = "images/animals/cow.png",
                            IsCorrect = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 153,
                            Answer = "images/animals/bunny.png",
                            IsCorrect = false,
                            QuestionId = 38
                        },
                        new
                        {
                            Id = 154,
                            Answer = "images/animals/goat.png",
                            IsCorrect = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 155,
                            Answer = "images/animals/chicken.png",
                            IsCorrect = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 156,
                            Answer = "images/animals/cat.png",
                            IsCorrect = false,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 157,
                            Answer = "images/animals/bunny.png",
                            IsCorrect = true,
                            QuestionId = 39
                        },
                        new
                        {
                            Id = 158,
                            Answer = "images/animals/dog.png",
                            IsCorrect = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 159,
                            Answer = "images/animals/chicken.png",
                            IsCorrect = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 160,
                            Answer = "images/animals/cat.png",
                            IsCorrect = true,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 161,
                            Answer = "images/animals/sheep.png",
                            IsCorrect = false,
                            QuestionId = 40
                        },
                        new
                        {
                            Id = 162,
                            Answer = "images/animals/cat.png",
                            IsCorrect = false,
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 163,
                            Answer = "images/animals/chicken.png",
                            IsCorrect = true,
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 164,
                            Answer = "images/animals/goat.png",
                            IsCorrect = false,
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 165,
                            Answer = "images/animals/horse.png",
                            IsCorrect = false,
                            QuestionId = 41
                        },
                        new
                        {
                            Id = 166,
                            Answer = "images/animals/bird.png",
                            IsCorrect = false,
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 167,
                            Answer = "images/animals/cat.png",
                            IsCorrect = false,
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 168,
                            Answer = "images/animals/bunny.png",
                            IsCorrect = false,
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 169,
                            Answer = "images/animals/cow.png",
                            IsCorrect = true,
                            QuestionId = 42
                        },
                        new
                        {
                            Id = 170,
                            Answer = "images/animals/dog.png",
                            IsCorrect = true,
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 171,
                            Answer = "images/animals/chicken.png",
                            IsCorrect = false,
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 172,
                            Answer = "images/animals/horse.png",
                            IsCorrect = false,
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 173,
                            Answer = "images/animals/sheep.png",
                            IsCorrect = false,
                            QuestionId = 43
                        },
                        new
                        {
                            Id = 174,
                            Answer = "images/animals/bear.png",
                            IsCorrect = false,
                            QuestionId = 44
                        },
                        new
                        {
                            Id = 175,
                            Answer = "images/animals/horse.png",
                            IsCorrect = false,
                            QuestionId = 44
                        },
                        new
                        {
                            Id = 176,
                            Answer = "images/animals/goat.png",
                            IsCorrect = true,
                            QuestionId = 44
                        },
                        new
                        {
                            Id = 177,
                            Answer = "images/animals/cat.png",
                            IsCorrect = false,
                            QuestionId = 44
                        },
                        new
                        {
                            Id = 178,
                            Answer = "images/animals/horse.png",
                            IsCorrect = true,
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 179,
                            Answer = "images/animals/chicken.png",
                            IsCorrect = false,
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 180,
                            Answer = "images/animals/sheep.png",
                            IsCorrect = false,
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 181,
                            Answer = "images/animals/dog.png",
                            IsCorrect = false,
                            QuestionId = 45
                        },
                        new
                        {
                            Id = 182,
                            Answer = "images/animals/bird.png",
                            IsCorrect = false,
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 183,
                            Answer = "images/animals/sheep.png",
                            IsCorrect = true,
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 184,
                            Answer = "images/animals/bunny.png",
                            IsCorrect = false,
                            QuestionId = 46
                        },
                        new
                        {
                            Id = 185,
                            Answer = "images/animals/cow.png",
                            IsCorrect = false,
                            QuestionId = 46
                        });
                });

            modelBuilder.Entity("MuteMate.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MuteMate.Server.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Colors",
                            Image = "images/colors/brown.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Animals",
                            Image = "images/animals/beartecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Letters",
                            Image = "images/Alphabet/a.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Letters",
                            Image = "images/Alphabet/b.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Letters",
                            Image = "images/Alphabet/c.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Letters",
                            Image = "images/Alphabet/d.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Letters",
                            Image = "images/Alphabet/e.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Letters",
                            Image = "images/Alphabet/f.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Letters",
                            Image = "images/Alphabet/g.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Letters",
                            Image = "images/Alphabet/h.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Letters",
                            Image = "images/Alphabet/i.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Letters",
                            Image = "images/Alphabet/j.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Letters",
                            Image = "images/Alphabet/k.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Letters",
                            Image = "images/Alphabet/L.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Letters",
                            Image = "images/Alphabet/m.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Letters",
                            Image = "images/Alphabet/n.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Letters",
                            Image = "images/Alphabet/o.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Letters",
                            Image = "images/Alphabet/p.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Letters",
                            Image = "images/Alphabet/q.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Letters",
                            Image = "images/Alphabet/r.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Letters",
                            Image = "images/Alphabet/s.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Letters",
                            Image = "images/Alphabet/t.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Letters",
                            Image = "images/Alphabet/u.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Letters",
                            Image = "images/Alphabet/v.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Letters",
                            Image = "images/Alphabet/w.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Letters",
                            Image = "images/Alphabet/x.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Letters",
                            Image = "images/Alphabet/y.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Letters",
                            Image = "images/Alphabet/z.png",
                            Question = "What letter is this?"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Colors",
                            Image = "images/colors/red.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Colors",
                            Image = "images/colors/blue.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Colors",
                            Image = "images/colors/green.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Colors",
                            Image = "images/colors/black.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Colors",
                            Image = "images/colors/white.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Colors",
                            Image = "images/colors/pink.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Colors",
                            Image = "images/colors/yellow.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Colors",
                            Image = "images/colors/grey.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Colors",
                            Image = "images/colors/purple.png",
                            Question = "What color is this?"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Animals",
                            Image = "images/animals/birdtecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Animals",
                            Image = "images/animals/bunnytecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Animals",
                            Image = "images/animals/cattecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Animals",
                            Image = "images/animals/chickentecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Animals",
                            Image = "images/animals/cowtecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Animals",
                            Image = "images/animals/dogtecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Animals",
                            Image = "images/animals/goattecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Animals",
                            Image = "images/animals/horsetecken.png",
                            Question = "What animal is this?"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Animals",
                            Image = "images/animals/sheeptecken.png",
                            Question = "What animal is this?"
                        });
                });

            modelBuilder.Entity("MuteMate.Server.Models.QuoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quote");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Praise",
                            Quote = "Wow, you’re really on a roll—keep up the great work!"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Praise",
                            Quote = "Amazing job! Every step you take is a leap forward!"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Praise",
                            Quote = "You’re shining brighter with every try—keep it up!"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Praise",
                            Quote = "Fantastic effort! You're making it look easy!"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Praise",
                            Quote = "You’re a natural—way to go!"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Encouragement",
                            Quote = "It’s okay to take your time—you’re learning and growing!"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Encouragement",
                            Quote = "Keep your chin up! Every try brings you closer to success!"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Encouragement",
                            Quote = "Don’t worry about mistakes—they help you learn and improve!"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Encouragement",
                            Quote = "Take a deep breath and give it another shot—you’ve got this!"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Encouragement",
                            Quote = "Every step, no matter how small, is progress!"
                        });
                });

            modelBuilder.Entity("MuteMate.Server.Models.UserAnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("QuestionId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MuteMate.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MuteMate.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuteMate.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MuteMate.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuteMate.Server.Models.AnswerModel", b =>
                {
                    b.HasOne("MuteMate.Server.Models.QuestionModel", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MuteMate.Server.Models.UserAnswerModel", b =>
                {
                    b.HasOne("MuteMate.Server.Models.AnswerModel", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuteMate.Server.Models.ApplicationUser", null)
                        .WithMany("UserAnswers")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("MuteMate.Server.Models.QuestionModel", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("MuteMate.Server.Models.ApplicationUser", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("MuteMate.Server.Models.QuestionModel", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
